import json, pathlib
src = json.load(open(r"docs\ref\presets.json", encoding="utf-8"))
order = ["pinpoint", "lookup", "chain", "sweep", "quick"]
src.sort(key=lambda p: order.index(p["name"]) if p["name"] in order else 99)
lines = []
lines.append("/* 由 query_planner.py 的 --json 输出生成，请勿手改数值。")
lines.append(" * 重新生成：")
lines.append(" *   python pipeline/lib/query_planner.py --json > docs/ref/presets.json")
lines.append(" *   python scripts/gen_web_presets.py")
lines.append(" * （预设的唯一真源是 pipeline/lib/query_planner.py） */")
lines.append("")
lines.append("import type { Preset } from './types'")
lines.append("")
lines.append("export const PRESETS: Preset[] = [")
for p in src:
    prm = p["params"]
    lines.append("  {")
    lines.append(f"    name: {json.dumps(p['name'])},")
    lines.append(f"    label: {json.dumps(p['label'], ensure_ascii=False)},")
    lines.append(f"    summary: {json.dumps(p['summary'], ensure_ascii=False)},")
    lines.append(f"    when: {json.dumps(p['when'], ensure_ascii=False)},")
    lines.append(f"    latency: {json.dumps(p['latency'], ensure_ascii=False)},")
    lines.append(f"    cost: {json.dumps(p['cost'], ensure_ascii=False)},")
    lines.append(f"    mode: {json.dumps(prm['mode'])},")
    lines.append(f"    top_k: {prm['top_k']},")
    lines.append(f"    chunk_top_k: {prm['chunk_top_k']},")
    lines.append(f"    max_entity_tokens: {prm['max_entity_tokens']},")
    lines.append(f"    max_relation_tokens: {prm['max_relation_tokens']},")
    lines.append(f"    max_total_tokens: {prm['max_total_tokens']},")
    rk = prm.get("enable_rerank", True)
    lines.append(f"    enable_rerank: {str(bool(rk)).lower()},")
    lines.append("  },")
lines.append("]")
lines.append("")
lines.append("export const PRESET_BY_NAME = Object.fromEntries(PRESETS.map(p => [p.name, p])) as Record<string, Preset>")
lines.append("")
pathlib.Path(r"web\src\api\presets.ts").write_text("\n".join(lines), encoding="utf-8")
print("wrote web/src/api/presets.ts", len("\n".join(lines)), "chars")
